version: '3'

services:  
  app:
    build: .
    entrypoint: ./.docker/app/entrypoint.sh
    container_name: Database-Transactions-Simulation-app
    ports:
      - 8080:8080
    networks:
      - Database-Transactions-Simulation-network
    volumes:
      - .:/go/Database-Transactions-Simulation
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine
    container_name: Database-Transactions-Simulation-db
    restart: always
    tty: true
    volumes:
      - ./.docker/postgres/dbdata:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple_bank
    networks:
      - Database-Transactions-Simulation-network

networks:
  Database-Transactions-Simulation-network:
    driver: bridge