version: '3'

services:  
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: database-transactions-simulation-app
    ports:
      - 8080:8080
    networks:
      - database-transactions-simulation-network
    volumes:
      - .:/goapp
    environment:
      - DB_SOURCE=postgresql://postgres:root@database-transactions-simulation-db:5432/simple_bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.3-alpine
    container_name: database-transactions-simulation-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple_bank
    networks:
      - database-transactions-simulation-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:14.3-alpine
    container_name: database-transactions-simulation-db-test
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple_bank_test
    networks:
      - database-transactions-simulation-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  database-transactions-simulation-network:
    driver: bridge