version: '3'

services:  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Database-Transactions-Simulation-app
    ports:
      - 8080:8080
    networks:
      - Database-Transactions-Simulation-network
    volumes:
      - .:/goapp
    environment:
      - DB_SOURCE=postgresql://postgres:root@Database-Transactions-Simulation-db:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

  postgres:
    image: postgres:14.3-alpine
    container_name: Database-Transactions-Simulation-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple_bank
    networks:
      - Database-Transactions-Simulation-network


networks:
  Database-Transactions-Simulation-network:
    driver: bridge