apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api-deployment
  template:
    metadata:
      labels:
        app: simple-bank-api-deployment
    spec:
      containers:
      - name: simple-bank-api
        image: 209967394362.dkr.ecr.sa-east-1.amazonaws.com/simplebank:c5e037d8e5e0c68b15d41920cd3f274fea294cf4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
