apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-deployment
  template:
    metadata:
      labels:
        app: simple-bank-deployment
    spec:
      containers:
      - name: simple-bank-deployment
        image: 756504842129.dkr.ecr.us-east-1.amazonaws.com/simplebank-my-ecr:e78f5065bb5a0d50a6475c6317062590994a546c
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
